### ISSUE TITLE
requirements.txt вместо venv/

### ISSUE THREAD

**Issue by IvanTemp** [Oleksandrigo/ranobelibParser#1]
Проект очень полезный. Спасибо.
Единственное, что не понравилось это `venv/`. Были какие-то причины делать так? К тому же в этой папке инфа о твоем компе.

**Comment by Oleksandrigo** [comment]
Я модифицировал один из модулей для парсинга

вт, 28 лют. 2023, 9:28 пп користувач IvanTemp ***@***.***>
пише:

**Comment by IvanTemp** [comment]
Окей, у меня и без модифицированных работает. Библы сам доставлял.

**Comment by Oleksandrigo** [comment]
Там картинки скачиваются криво без модификации

ср, 1 бер. 2023, 12:34 пп користувач IvanTemp ***@***.***>
пише:
