### ISSUE TITLE
Ошибка в README или main.py

### ISSUE THREAD

**Issue by IvanTemp** [Oleksandrigo/ranobelibParser#2]
https://github.com/Oleksandrigo/ranobelibParser/blob/5f6927b962883cd6bb94a0a63ce4f9afaf1362b1/README.md?plain=1#L10-L11
А в коде идет проверка на "?"
https://github.com/Oleksandrigo/ranobelibParser/blob/5f6927b962883cd6bb94a0a63ce4f9afaf1362b1/main.py#L44-L45

Предлагаю такие варианты решения: либо поправить описание, ведь т.к. на самом деле нужен "?" в ссылке. Либо добавить обработку такого случая. Либо удалить в коде эти строки.

**Comment by IvanTemp** [comment]
И да. Я пишу проблемы потому что мне понравился проект, а не наоборот)

**Comment by Oleksandrigo** [comment]
Кажись это тоже обрабатывается, так что все в порядке

ср, 1 бер. 2023, 12:33 пп користувач IvanTemp ***@***.***>
пише:

**Comment by IvanTemp** [comment]
Так вроде нет? 
У тебя стоит создание пустой строки, а далее изменение только при хотя бы одном из двух условий. 
Ну то есть, если вставить пример из readme, то функция выдаст пустую строку.

**Comment by Oleksandrigo** [comment]
Нет, функция работает корректно, это проверка для лентяев которые не убирают другую часть ссылки.

**Comment by IvanTemp** [comment]
![d78c63da70c68d6b37f412f49dd2c19c](https://user-images.githubusercontent.com/78906461/228091312-fd003d8d-5ae7-42f7-8292-a7e98397fc6f.jpg)
