### ISSUE TITLE
Не работает ModuleNotFoundError

### ISSUE THREAD

**Issue by ryadik** [Oleksandrigo/ranobelibParser#5]
Привет, при запуске из start.bat и через python main.py вылазит ошибка
пробовал на пайтоне 3.9.6 и 3.11.5

`ModuleNotFoundError: No module named docx, line 4`

я через pip установил этот модуль, но вылезла следующая ошибка

`ModuleNotFoundError: No module named exception, line 30`

мб надо как-то зависимости поставить? в ридмике ничего про это не написано, да и я в пайтоне не особо шарю.
подскажи, пожалуйста, как зафискить?

**Comment by K1nGsmaN-hub** [comment]
В общем, я сделал свой, надоело ждать ответа.
Если кто читатет этот ишьюк, то вот он [*опаньки*](https://github.com/K1nGsmaN-hub/ranobelib-parser)

**Comment by ryadik** [comment]
В общем, я сделал свой, надоело ждать ответа.
Если кто читатет этот ишьюк, то вот он [*опаньки*](https://github.com/K1nGsmaN-hub/ranobelib-parser)
